version: '2'
services:
  interactiveserver-app:
    image: interactiveserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://interactiveserver-mssql:1433;database=InteractiveServer
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  interactiveserver-mssql:
    extends:
      file: mssql.yml
      service: interactiveserver-mssql
